### ISSUE TITLE
Curved Mesh Adaptation Assertion

### ISSUE THREAD

**Issue by JaredCrean2** [SCOREC/core#247]
I ran into an assertion error when adapting a curved mesh.  I developed a stand-alone test case in `/users/creanj/lore/test_ma_quadratic3`, which uniformly refines the mesh.The output is:

```
~/lore/test_ma_quadratic3$ test_init3 airfoil40_mesh1_curve_.smb airfoil40.smd 
Entered init

geoname = airfoil40.smd
initializing geo_sim
loading geometric model
finished loading geometric model
finished loading mesh
adapt iteration 0
after adaptation, numEl = 12296
adapt iteration 1
after adaptation, numEl = 49184
adapt iteration 2
after adaptation, numEl = 196736
adapt iteration 3
after adaptation, numEl = 786944
adapt iteration 4
after adaptation, numEl = 3147776
adapt iteration 5
ev[0] == vert || ev[1] == vert failed at /users/creanj/lore/build/core_simmetrix/apf/apfSimplexAngleCalcs.cc + 28 
Aborted (core dumped)
```

The backtrace is:

```
#0  0x00007fffeba7b2c7 in raise () from /lib64/libc.so.6
#1  0x00007fffeba7c9b8 in abort () from /lib64/libc.so.6
#2  0x00007fffece283c8 in PCU_Assert_Fail (
    msg=msg@entry=0x7fffffff4d30 "ev[0] == vert || ev[1] == vert failed at /users/creanj/lore/build/core_simmetrix/apf/apfSimplexAngleCalcs.cc + 28 \n") at /users/creanj/lore/build/core_simmetrix/pcu/pcu_util.c:16
#3  0x00007fffed6c305b in apf::computeEdgeTangentAtVertex (m=<optimized out>, edge=edge@entry=0x7434a62, vert=vert@entry=0x1, Q=...)
    at /users/creanj/lore/build/core_simmetrix/apf/apfSimplexAngleCalcs.cc:21
#4  0x00007ffff798f394 in crv::EdgeReshaper::repositionEdge (this=<optimized out>, edge=0x8768ea, this=<optimized out>, this=<optimized out>, 
    this=<optimized out>, this=<optimized out>, this=<optimized out>, this=<optimized out>, this=<optimized out>, this=<optimized out>, 
    this=<optimized out>, this=<optimized out>, this=<optimized out>) at /users/creanj/lore/build/core_simmetrix/crv/crvShape.cc:275
#5  0x00007ffff798f706 in crv::EdgeReshaper::apply (this=0x7fffffff6020) at /users/creanj/lore/build/core_simmetrix/crv/crvShape.cc:201
#6  0x00007fffed67a3ae in apf::CavityOp::applyLocallyWithModification (this=0x7fffffff5f90, d=2)
    at /users/creanj/lore/build/core_simmetrix/apf/apfCavityOp.cc:44
#7  0x00007fffed67a975 in apf::CavityOp::applyToDimension (this=this@entry=0x7fffffff5f90, d=2)
    at /users/creanj/lore/build/core_simmetrix/apf/apfCavityOp.cc:110
#8  0x00007fffee93496f in ma::applyOperator (a=a@entry=0x8ba5d0, o=o@entry=0x7fffffff6020)
    at /users/creanj/lore/build/core_simmetrix/ma/maOperator.cc:49
#9  0x00007ffff798e9e7 in repositionInvalidEdges (a=0x8ba5d0) at /users/creanj/lore/build/core_simmetrix/crv/crvShape.cc:583
#10 crv::fixInvalidEdges (a=a@entry=0x8ba5d0) at /users/creanj/lore/build/core_simmetrix/crv/crvShape.cc:597
#11 0x00007ffff7971e64 in crv::fixInvalidElements (a=a@entry=0x8ba5d0) at /users/creanj/lore/build/core_simmetrix/crv/crvAdapt.cc:168
#12 0x00007ffff79724d8 in crv::adapt (in=0xec4fd0) at /users/creanj/lore/build/core_simmetrix/crv/crvAdapt.cc:226
#13 0x0000000000401a0f in adaptUntilError (m=0x8bc460, itermax=10) at /users/creanj/.julia/v0.6/PumiInterface/src/test_init3.cc:28
#14 0x0000000000401d00 in main (argc=3, argv=0x7fffffff6528) at /users/creanj/.julia/v0.6/PumiInterface/src/test_init3.cc:81
```

**Comment by JaredCrean2** [comment]
@cwsmith ping

**Comment by cwsmith** [comment]
At first glance, the assertion appears to be indicating that the 'vert' is not adjacent to the edge being evaluated.  @mortezah, any thoughts on this?

**Comment by mortezah** [comment]
@JaredCrean2 can you tell me the branch/commit of the core that you are using?

**Comment by JaredCrean2** [comment]
```
commit ac77deda8998991870bd379f6d94c56886130aed
Author: Fan Yang <yangf4@rpi.edu>
Date:   Thu Jul 4 16:37:03 2019 -0400

    add new nodal field hmin_flag
```

**Comment by mortezah** [comment]
I'll take a look at this (hopefully by the end of today) and let you know.
