### ISSUE TITLE
conversion of quadratic simmetrix meshes is broken

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/core#82]
The model and mesh are attached.  The execution of convert and the SCOREC/core git hash is below. 

```
+cwsmith@pachisi: /fasttmp/cwsmith/nightlyBuilds/repos/core (master)$ gitlog | head -1
8a4b1d6 (HEAD, origin/master, origin/HEAD, master) Merging develop into master
+cwsmith@pachisi: $ which convert
/usr/local/pumi/core//bin/convert
+cwsmith@pachisi: /lore/cwsmith/geometries/svnMeshes/plate $ convert plate.smd quad36_curved.sms quad36_curved.smb
read and created the simmetrix mesh in 0.001219 seconds
created the apf_sim mesh in 0.000100 seconds
transferring quadratic mesh
Segmentation fault
```

GDB stack trace

```
read and created the simmetrix mesh in 0.001184 seconds
created the apf_sim mesh in 0.000104 seconds
transferring quadratic mesh

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff728bf50 in P_coord(MPoint*, double*) () from /usr/local/pumi/core//lib/libapf_sim.so
+(gdb) where
#0  0x00007ffff728bf50 in P_coord(MPoint*, double*) () from /usr/local/pumi/core//lib/libapf_sim.so
#1  0x00007fffee5a1054 in apf::FieldDataOf<double>::getNodeComponents (this=0x9c5890, e=0x9f4910, node=0,
    components=0x96cee0) at /fasttmp/cwsmith/nightlyBuilds/repos/core-shared/apf/apfFieldData.cc:202
#2  0x00007fffee5a5772 in apf::Converter::run() () from /usr/local/pumi/core//lib/libapf.so
#3  0x00007fffee5a3d2b in apf::convert (in=<optimized out>, out=0x96cee0)
    at /fasttmp/cwsmith/nightlyBuilds/repos/core-shared/apf/apfConvert.cc:262
#4  0x00007fffef5b4f5e in MeshMDS (from=<optimized out>, m=<optimized out>, this=<optimized out>)
    at /fasttmp/cwsmith/nightlyBuilds/repos/core-shared/mds/apfMDS.cc:132
#5  apf::createMdsMesh (model=0x96c8f0, from=0x9de420)
    at /fasttmp/cwsmith/nightlyBuilds/repos/core-shared/mds/apfMDS.cc:676
#6  0x00000000004148d2 in main (argc=4, argv=0x7fffffffde28)
    at /fasttmp/cwsmith/nightlyBuilds/repos/core-shared/test/convert.cc:113
+(gdb)
```

[plate.tar.gz](https://github.com/SCOREC/core/files/804770/plate.tar.gz)

**Comment by mortezah** [comment]
This is fixed as of  c0eed1. This fix assumes the quadratic quad meshes generated by simmetrix are serendipity as opposed to 2nd order Lagrange (the former does not have a face node while the latter does). 

I will close this when I get a response from simmetrix confirming the above assumption.

**Comment by mortezah** [comment]
Simmetrix confirmed that they don't have face nodes for quadrilateral elements. I am closing this for now.
